# Generated by Django 3.2.3 on 2025-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_id', models.CharField(max_length=50, unique=True)),
                ('register_number', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('identifying_characteristics', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('origin_place', models.CharField(blank=True, max_length=255)),
                ('register_type', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('loss_place_description', models.TextField(blank=True)),
                ('rnom_register_number', models.CharField(blank=True, max_length=100)),
                ('dokm_base_document', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('museum', models.CharField(blank=True, max_length=255)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('date_creator', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
